### ISSUE TITLE
SDチャンネルにおいて字幕が引き伸ばされる件

### ISSUE THREAD

**Issue by anothergogo** [xtne6f/TVCaptionMod2#2]
はじめまして。いつもありがたく使わさせていただいています。
さて、TOKYO MX2やスカパーなどのSDチャンネルの番組を見ていると、字幕が横に引き伸ばされるのが気になります。
おそらくこれが仕様上は正常な動作なのだろうとは思いますが、画面を占領してしまいますので、HDチャンネルと同じサイズになるようにしていただければ幸いです。
よろしくお願いします。

**Comment by xtne6f** [comment]
実機でもやはり引き伸ばされるので、推察のとおり恐らく仕様です。気になりますよね。
調整するかどうかの選択肢を設けようと思います。

**Comment by anothergogo** [comment]
ご対応いただけるとのことで大変ありがたいです!
ぜひ、よろしくお願いします。

**Comment by xtne6f** [comment]
17201eda8f1692fff68e0e97dc9b24b97bb03f52 で対応しました。

**Comment by anothergogo** [comment]
ご返信が遅くなり申し訳ありません。
以前に比べて格段に見やすくなりました。ご対応いただき感謝しています。
ありがとうございました。
