### ISSUE TITLE
一部フォントを指定すると文字が縦長に表示される件

### ISSUE THREAD

**Issue by anothergogo** [xtne6f/TVCaptionMod2#3]
もう1件、issuesに失礼します。
游ゴシックやGoogleのNoto sans・Noto serif、Adobeの源ノ角ゴシック・源ノ明朝など一部のフォントで、日本語の文字が縦長に表示される不具合に悩まされています。
対処療法的に縦横比を200%程度にして使用していますが、こうすると今度は英数字が重なり合い読みにくくなってしまいます。
もし可能でしたら、根本的な解決をしていただければ幸いです。よろしくお願いします。

**Comment by xtne6f** [comment]
個別のフォントについて詳しくは分かりませんが、それらは恐らくプロポーショナルフォントなので、このプラグインが表示する字幕の仕様とは基本的に相容れません。縦横比指定による対処は「ほとんど固定幅だがプロポーショナルとして収録されている」フォントのためのものと考えてください。
字幕自体をプロポーショナルに表示する方向の解決もありかと思いますが、画面に被さる位置が変わってしまうので今のところ微妙に思います。

**Comment by anothergogo** [comment]
すみません。あの後、当方で少し検証してみましたが、AvoidHalfAlphaを1にすれば解決できました。
ご面倒をおかけしてしまい、申し訳ありませんでした。
ただ、AvoidHalfAlphaは半角数字には効かないようです。通常はこれでいいのですが、フォントによっては半角数字にも適用したい場合がありますので、**別オプションで**対応していただけるとありがたいです。また、プロパティ画面内にも項目を設けてくださると、大変ありがたいです。

参考までに、当方で検証した結果を添付します。
![170415155120 002499greenshot](https://cloud.githubusercontent.com/assets/22254553/25061560/33563ec0-21f4-11e7-904e-367ffc976e88.png)
上の画像は、源ノ角ゴシックHeavyをAvoidHalfAlpha=0で適用した場合の様子です。
一番下の青文字は全角英数字(ＡＢＣＤＥ…)を半角表示(CP_STR_MEDIUM)した場合ですが、ご覧の通り一部のアルファベットが重なってしまっています。

![170415155434 002500greenshot](https://cloud.githubusercontent.com/assets/22254553/25061565/43e9637a-21f4-11e7-8482-baf2657b109e.png)
上の画像は、源ノ角ゴシックHeavyをAvoidHalfAlpha=1で適用した場合の様子です。
ご覧の通り、一番下の青文字のアルファベットが重なりが解消されています。一方で、数字には適用されていないようで、フォントによっては数字が若干重なってしまっているのが気になります。

なお、全角カタカナを半角表示した場合は、AvoidHalfAlphaを適用しない場合でも特に問題はありませんでした。

**Comment by xtne6f** [comment]
検証感謝します。現在、数字やその他の約物は常に可能ならASCIIコード(いわゆる半角)へ置換して描画しますが、これらについても設定できたほうがよさそうですね。
efbb36b23072f6a0ba7a308ddca4ecab7dc500ed でAvoidHalfAlphaを置きかえAvoidHalfFlagsとして対応してみました。設定値+1で英字、+2で数字、+4でその他に対する置換がオフになります。
設定画面への追加については、すでに画面がだいぶ縦長になっていることもあって、ちょっと保留します。オフにすると文字が縦長になることは避けられないので、なるべく固定幅フォントの使用に誘導したい意図もあります。
なお、半角カナは常に全角カナを縦長にして描画しています。半角カナには濁点付き文字が用意されていないのが主な理由です。

**Comment by anothergogo** [comment]
少々混乱しましたが、AvoidHalfFlagsオプションは、
0のときオフ
1のとき英字のみ適用
2のとき数字のみ適用
3のとき英字と数字に適用
ということですね。
確かに文字が縦長にはなってしまいますが、文字の重なりは英字・数字とも解消されましたので、しばらくこの設定で使用したいと思います。
ご対応いただき、大変感謝しています。ありがとうございました。
