### ISSUE TITLE
ふりがなを除去する機能について

### ISSUE THREAD

**Issue by anothergogo** [xtne6f/TVCaptionMod2#4]
またお世話になります。今回はふりがな除去機能についてです。
ふりがな除去機能は、ふりがなを除去することはできても、行間を詰めることまではできないようです。
そのため、ふりがな付きの字幕が複数行ある場合にこの機能を使うと、不自然な間ができてしまうことがあるのがいつも気になっています。
特にアニメ番組など、全ての漢字にふりがなが振ってあるような番組でよく発生します。
ご面倒をおかけしますが、ご対応いただけると大変ありがたいです。なにとぞよろしくお願いします。

**Comment by xtne6f** [comment]
詰め方向について、例えば1行目と2行目に接するふりがなを取り除く場合、ざっくりと
(1)上に詰める、(2)下に詰める、(3)互いに歩み寄る
があると思いますが、なにか他に案ありますでしょうか。
3行目以降がある場合の処理などを考えると実装が楽なのは恐らく(1)なので、とりあえずこれで様子をみて試してみようと思います。

**Comment by anothergogo** [comment]
1の方法というのは、ふりがなの行を抜かして、本文を上の行から順次描写していくというものでしょうか。たしかに簡単そうですね。
2の方法も、1の方法で抜かした行の数を数えることができれば、その分だけ下にずらせば実現できそうですね。字幕は大概下に詰められているものなので、2の方法が使えると嬉しいですね。
3の方法は意義を見出しづらいですね。実装も複雑そうに感じます。
というわけで、1の方法をベースに2の方法を実装するのが最も良いように思います。ご参考になれば幸いです。

**Comment by xtne6f** [comment]
1で試してみたところやはり微妙でした。2の方法を実装しました。
IniファイルのShiftSmallキーまたは設定画面から設定してください。設定画面ではグレーアウトしますが、ShiftSmallキーはIgnoreSmallキーとは独立の設定なので、IgnoreSmall=0、ShiftSmall=1、とすると動作検証に少し便利です。
あと、設定画面のテストボタンの表示では上に詰めてしまいますが仕様です。

**Comment by anothergogo** [comment]
実装お疲れ様でした。早速試してみましたが、不具合等は特に見受けられません。
行間を狭められるようになったことで、ふりがなを除去した時でも字幕が読みやすくなりました。本当に素晴らしいです。
大変感謝しています。ありがとうございました。
