### ISSUE TITLE
アンダーライン指定が太字として描画される

### ISSUE THREAD

**Issue by monyone** [xtne6f/TVCaptionMod2#5]
いつも TVCaptionMod2 を有難く使わせてもらっております。
オープンソースソフトウェアでのARIB字幕のレンダラーであるため、日々参考にさせて頂いております。
このソフトウェアがオープンソースでの8単位符号レンダラーの事実上の基準となっているかと思います。

色々と番組を見ていたところ、アンダーライン指定で運用基準と異なる動作をしているため、issue を立てました。
意図して運用基準とは異なる描画をしているのであれば、この issue は閉じてください。

## 前提

運用基準で定められている通りに、字幕に STL/SPL で 下線(アンダーライン) を表記する番組が存在します。
例えば、Eテレ0655&2355 で字幕がある場合 (大晦日など) の際、55 の表記に対して STL/SPL を用いて下線を表示します。

## 現在の動作

下線(アンダーライン)指定されている文字列が、下線ではなく、字体の太字(ボールド)化で描画されています。

## 期待する動作

1 ドット幅の下線が前景色で引かれれれば、運用基準と合致するため、その方が好ましいかと思います。
TSから確認したため、実際のテレビでの描画を確認できておらず、好ましいという表現を用いています。

## 補足
補足として、運用基準での STL/SPL の記述を記載いたします。
少し古いものではありますが、入手できるものが古いバージョンしかなかったため、ご了承ください。

### 地上波の運用基準
ARIB TR-B14 6.0版 (第二分冊) p3.1.119 より抜粋
> STL アンダーライン開始およびモザイク分離開始 アンダーラインのみ運用する
> SPL アンダーライン終了およびモザイク分離終了 アンダーラインのみ運用する

ARIB TR-B14 6.0版 (第二分冊) p.3.1.124 より抜粋
> 4.5.5 アンダーラインの運用
> アンダーラインは、表示区画内の外側に1ドットの幅で描画する。
> ここで、横書きの場合には、次の行の側の辺に付加し、縦書きの場合には、前の行の側の辺に付加するものとする。

### BS・CSの運用基準

ARIB TR-B15 6.9版 (第一分冊) p3.1.107 より抜粋
> STL アンダーライン開始およびモザイク分離開始 アンダーラインのみ運用する
> SPL アンダーライン終了およびモザイク分離終了 アンダーラインのみ運用する

ARIB TR-B15 6.9版 (第一分冊) p.3.1.111 より抜粋
> 7.5.5 アンダーラインの運用
> アンダーラインは、表示区画内の外側に1ドットの幅で描画する。
> ここで、横書きの場合には、次の行の側の辺に付加し、縦書きの場合には、前の行の側の辺に付加するものとする。

**Comment by xtne6f** [comment]
ありがとうございます。意図せずです。
レンダラーのほうの対応は一応できているのですが、`ARIB8CharDecode.cpp` のSPL/STLの記述が変ですね。

レンダラーのほうですが、規格上は1ドット幅(標準の表示区画の高さの1/24)ですが、出現頻度を考えるとWin32APIの下線の動作でもいいかなと考えています。
現状は↓のようになっています。
![ul](https://user-images.githubusercontent.com/2673799/116786004-8de1ad00-aad7-11eb-9104-4068dceccefb.png)

**Comment by monyone** [comment]
ご返信ありがとうございます。
`m_bUnderLine` を `ARIB8CharDecode.cpp` で変更すれば反映されるという理解で大丈夫そうでよかったです。

1ドット幅については、厳密には、ARIBでは以下のように規定されています。

- ARIB STD-B24 (標準規格): 標準の表示区画の高さの 1/24 ドット幅
- ARIB TR-B14/TR-B15 (運用規定): 1 ドット幅

標準規格に沿うか、運用規定に沿うのかの判断が必要ですが、
実用的には運用規定に従うのがテレビに近くなるのかなと思います。

また、アンダーラインは囲み文字の下枠と同じ描画位置だと 運用基準 (TR-B14/TR-B15) では書かれています。
以下の記述が囲み文字の記載と同じであるためです。
(自作のライブラリでは囲み文字と同じような処理にしています)

> 表示区画内の外側に1ドットの幅で描画する。

一般的なテレビと同じ表示にするには、Win32APIの下線の動作ではよろしくないのかもしれません。

**Comment by xtne6f** [comment]
>表示区画内の外側に1ドットの幅で描画する。

これって素直にとるとやはり↓の意味なんでしょうかね。
![ul](https://user-images.githubusercontent.com/2673799/116790516-78787d00-aaef-11eb-8e34-ee5861d93b23.png)
これだと別段アンダーラインの規定設けなくても(囲みで表現できる)、みたいな気分ですが
「強調」の意味論として設けられてるのかな。とりあえずこっちでいきます。

**Comment by monyone** [comment]
画像の通りの描画が ARIB の運用規定の動作だと、僕は思っています。

ただ、「XXという理由があって、Win32API の下線を用いて表示しています」という注記さえあれば、
TVCaptionMod2 の字幕表現自体は ARIB のルールから離れてもよいと思います。
テレビより良い表現になるなら、そっちの方が TVCaptionMod2 を利用する方にとって理想的でしょう。
僕個人としても、Win32API の GDI で描画する下線の方が見やすいと思いますし。

実際の所、TVCaptionMod2 の動作がオープンソース字幕レンダラのリファレンスとなっているようでして、
TVCaptionMod2 のこの挙動は、こういう理由で ARIB の仕様に必ずしも合致しているわけではない、と説明できると
オープンソースで別に字幕レンダラを作っている立場としては説明がしやすい、といった事情がありまして...。

なので、但し書きさえあれば、Win32APIの下線の動作でいいんじゃないかなと思っています。

**Comment by xtne6f** [comment]
迷ったのですが、装飾関係のパラメータが変わって文字列の分割が行われたときに、下線が飛び飛びになって汚くなるのでは？という懸念が生まれたので、規格通りの囲みでの表現としました。ありがとうございました。

// 年越し2355、毎年見てるんですが録っときゃ良かった…
