### ISSUE TITLE
字幕が常に縁取りされてしまう

### ISSUE THREAD

**Issue by monyone** [xtne6f/TVCaptionMod2#6]
いつも TVCaptionMod2 を有難く使わせてもらっております。
オープンソースソフトウェアでのARIB字幕のレンダラーであるため、日々参考にさせて頂いております。
このソフトウェアがオープンソースでの8単位符号レンダラーの事実上の基準となっているかと思います。

見たところ、常に字幕を縁取っているため、この issue を立てました。
意図して字幕を常に縁取っているのであれば、この issue は閉じてください。

## 前提

標準規格(ARIB STD-B24) では、ORN によって縁取り指定がされている場合にのみ、縁取りします。

> オープンソースでの8単位符号レンダラーの事実上の基準になっているかと思います。

と記述しました通り、オープンソースの字幕レンダラーを作っている際に、TVCaptionMod2 が常に縁取りを行うため、
「TVCaptionMod2 が縁取るのに、この字幕レンダラーが縁取らないのはバグなのではないか?」というご指摘と、
「常に縁取りする TVCaptionMod2 の動作をデフォルトとしてほしい」という要望をいただくことがあります。

## 現在の動作

常に字幕が縁取りされているように見受けられます。

## 期待する動作

縁取り指定されていない字幕に対して、縁取りがデフォルトではされないのが理想です。
また、縁取りの色が固定されているように見受けられますが、色をCSIのパラメータから取得するのが理想です。
オプションとして常に縁取りをするというのが良いのかと思っております。

### 標準規格

ARIB STD-B24 6.2版 (第一分冊) p.110 より抜粋

> ORN 縁取り指定
> 　CSI: 09/11
> 　P1: 03/0: 文字飾り無し, 03/1: 縁取り, 03/2: 影付き, 03/3: 中抜き
> 　I1: 03/11 (中間文字)
> 　P21P22: 03/0 ~ 03/9 カラーマップアドレスの上位4ビット
> 　P23P24: 03/0 ~ 03/9 カラーマップアドレスの下位4ビット
> 　I2: 02/0 (中間文字)
> 　F: 06/3 (終端文字)

**Comment by xtne6f** [comment]
縁取りについては、ORNとは関係なく「見やすさ」でつけた、あるいはもっと消極的に、前身のTVCaptionについてたので仕様継承したものと記憶しています。つまり、今あるフチは、ORNの縁取りではありません。

そのうえで、縁取りについては、デフォルトでは残す方向でいこうと思います。
実機のテレビでは、基本、視認性に優れた太めの丸ゴシックが使われると思いますが、このようなプラグインの場合、フォントを気にしないカジュアルユーザー(たぶん多数派)はOSについてくる適当なフォントを使うことになります。そしてこういうフォントは線が細いので、背景が50%透過の黒であっても、フチで補強しないとやや厳しいです(と思います)。

ただ、デフォルトのフチの太さ(5dot)は太すぎるなぁ…と最近思っています。デフォルトでは2dotぐらいに減らして、ORNのフチを+3dotぐらいで表現するよう変更しようと思います。

>「TVCaptionMod2 が縁取るのに、この字幕レンダラーが縁取らないのはバグなのではないか?」というご指摘

これはもう説明不足です(^^;。Readmeになんか書いておきます。

**Comment by monyone** [comment]
ご返信ありがとうございます。

> ただ、デフォルトのフチの太さ(5dot)は太すぎるなぁ…と最近思っています。デフォルトでは2dotぐらいに減らして、ORNのフチを+3dotぐらいで表現するよう変更しようと思います。

現行の縁取りが変わってしまうのも、利用者にとって厳しいものがあるかと思います。

>「TVCaptionMod2 が縁取るのに、この字幕レンダラーが縁取らないのはバグなのではないか?」というご指摘

という懸念の部分が TVCaptionMod2 側で、常に縁取りしていると説明している資料があれば、
動作としては ORN によらずに 5px 縁取りの現状ママで良いかと思います。

**Comment by xtne6f** [comment]
現状のフチの太さに規格上の根拠はないので、たんに見た目の問題として、
![stroke](https://user-images.githubusercontent.com/2673799/116840653-9b02b700-ac11-11eb-93b3-20af6bce9be7.png)
を見比べたときに、3(dot)あたりが視認性と重さのバランスがいいかなぁ、みたいなことです。

2～3dotあたりの太さをデフォルトにして、ORNを+3(5～6dot)で表現する計画です。
フチの太さは設定ダイアログで自由に変えられるので、デフォルトは多くの人が無難に使える値が目標になります。

**Comment by xtne6f** [comment]
迷った結果 83f2cf0d2d398e9b23cd57ee022fc7cf06996a84 で決着しました。
常時縁取りのデフォルトを3dotに縮小、ORN縁取りのデフォルトを5dotとして、設定項目を1つ増やします↓
![orn](https://user-images.githubusercontent.com/2673799/116998769-ae00ae80-ad19-11eb-8c04-54d28594bc0c.png)

色パラメータについては、パーサーは実装しましたが、今のところ黒で送ってくる実データしか得られていないこともあって、レンダラの実装を先送りします。
