### ISSUE TITLE
デフォルトマクロ文でJIS互換漢字1面が指定されている

### ISSUE THREAD

**Issue by monyone** [xtne6f/TVCaptionMod2#7]
いつも TVCaptionMod2 を有難く使わせてもらっております。
オープンソースソフトウェアでのARIB字幕のレンダラーであるため、日々参考にさせて頂いております。
このソフトウェアがオープンソースでの8単位符号レンダラーの事実上の基準となっているかと思います。

この動作が意図したものであるならば、この issue は閉じてください。

## 現在の動作

デフォルトマクロ文として、漢字系集合 (0x42) ではなく、JIS互換漢字1面 (0x39) が指定されています。

## 期待する動作

  デフォルトマクロ文として、漢字系集合 (0x42) を指定するのが理想か思います。

## 補足

TVCaptionMod2 の動作としては、漢字系集合もJIS互換漢字1面もJIS互換漢字2面も同じ動作をするようですので、描画の問題はありません。

**Comment by xtne6f** [comment]
ありがとうございます。意図したものではないです。
経緯を想像すると、ARIB8CharDecode.cppのコードベースはFriioViewまで遡りますが、これはもともとPSI/SI(EPGデータなど)用のモジュールであったために、PSI/SIの初期化動作の規定が、字幕の初期化動作に紛れ込んだものと思われます。

Cプロファイル(ワンセグ)のほう(便宜上`m_wSWFMode==14`として、`m_G2.iMF = MF_JIS_KANJI1;`と書いてある部分)もTR-B14で漢字系集合となっているので、同様に漢字系集合が正しいです。

プルリク歓迎です(面倒そうならこちらで直します)。

**Comment by monyone** [comment]
ご返信ありがとうございます。

自分の環境では windows のビルド環境やらを整える必要があり、古いマシンで HDD の容量が厳しく...
という状態でして、ちょっと PR を投げる場合は時間がかかりそうです。

デフォルトマクロ文は `0x1B,0x24,0x39` が `0x1B,0x24,0x42` になるだけですので 
(デフォルトマクロで漢字系集合を指定するのはG0へのセットしかない) 、そちらで直してもらった方が早いかと思います...

**Comment by xtne6f** [comment]
規格に沿って漢字系集合(0x42)に変更しました。
